[package]
name = "networking-dive"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
libc = "0.2"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
